# Created by Nathanne Isip
# GitHub repository at: https://github.com/nthnn/oledimg

import logging
import numpy as np
import os
import sys
import warnings
from PIL import Image

if len(sys.argv) != 3:
    print("Image to OLED Array Converter\n")
    print("Usage: oledimg.py [image] [output]")
    print("    - image: The input to be converted.")
    print("    - output: The output C/C++ file.")
    exit(0)

warnings.filterwarnings('ignore')
logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p', level=logging.INFO)

filename = sys.argv[1]
if not os.path.exists(filename) or not os.path.isfile(filename):
    logging.error("Input file doesn't exists.")
    exit(0)

logging.info("Reading image file...")

pim = Image.open(filename)
colors = np.array(pim.convert("RGB"))

white_y, white_x = np.where(np.all(colors==[255, 255, 255], axis=2))
width, height = pim.size

imagename = os.path.splitext(os.path.basename(filename))[0]
output = "// Generated by oledimg.py\r\n"
output += "// Check oledimg tool out at https://github.com/nthnn/oledimg\r\n\r\n"
output += "static const uint8_t PROGMEM " + imagename + " = {"

logging.info("Converting to OLED image bitmap array...")
for y in range(height):
    output += "\r\n    {"

    for x in range(width):
        if x in white_x and y in white_y:
            output += "1, "
        else:
            output += "0, "

    output = output[:-2]
    output += "},"

output = output[:-1]
output += "\r\n};\r\n"
logging.info("Converting done!")

fileout = open(sys.argv[2], "w")
fileout.write(output)
fileout.close()

logging.info("Task done!")